theme: jekyll-theme-minimal

<html>

<head>
<title>Blog-post test</title>
</head>


<body>
<h1>Ranking Popular Python Packages for Data Science</h1>

<p>At <a href="https://www.thedataincubator.com/">The Data Incubator</a>, we pride ourselves
on having the latest data science curriculum.  Much of our curriculum is based
on feedback from corporate and government partners about the technologies they
are looking to learn.</p>

<h2><code>numpy</code>, <code>tensorflow</code>, and <code>pandas</code> are top 3</h2>

<p>The interactive interpreter <code>ipython</code> is fourth overall, while the <code>jupyter</code>
project (of the popular notebook) is 19th overall (not shown).</p>

<h2>Github vs. Stack Overflow activity</h2>

<p>There appears to be an inverse correlation in Github activity compared to Stack
Overflow and Downloads for the top packages. For example, there are a lot of
Stack Overflow questions for <code>numpy</code> and <code>pandas</code> compared to <code>tensorflow</code> and
<code>scikit-learn</code>, but the latter two have an edge on Github. Since <code>numpy</code> and
<code>pandas</code> are two "utility" packages, perhaps more people are actually using
them (and need help).</p>

<h2><code>matplotlib</code> most popular graphics library</h2>

<p>As expected, <code>matplotlib</code> (2D plotting library) is the most popular graphics
package, but the ranking also features <code>plotly</code> (interactive,
publication-quality graphs that can be easily published online) and <code>bokeh</code> (an
interactive visualization library that targets modern web browsers for
presentation). <code>ggpy</code> (Python port for R's popular <code>ggplot2</code> package) was 18th
overall, but the data is less reliable, as noted in the next section.</p>

<h1>Limitations</h1>
<p>Importantly,
the <a href="https://www.continuum.io/anaconda-overview">Anaconda distribution</a> bundles
together many of these packages, and this was not considered.</p>

<p>Further, naturally, some packages that have been around longer will have higher
metrics, and therefore higher ranking. This is not adjusted for in any way.</p>


</body>
</html>
